_BASE_: "base_r50_4x_clip.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis_image_exemplar_features_avg_K-005_author.npy'
    USE_BIAS: -2.0
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
